Repository back-stage/WeekBack, pull requests merged in 2021-02, with the labels that each got.

#38 [1기] 4주차 목표
  1th/week_4/lena.md
Labels: 목표달성, 주간목표

#40 [1기] 4주차 목표
  1th/week_4/Jay.md
Labels: 주간목표, 피드백

#36 [1기] 4주차 목표
  1th/week_4/Solar.md
Labels: 목표달성, 목표수정, 주간목표, 피드백

#43 [1기] 5주차 목표
  1th/week_5/Solar.md
Labels: 목표달성, 주간목표, 피드백

#46 [1기] 5주차 목표
  1th/week_5/Poogle.md
Labels: 목표달성, 주간목표

#45 [1기] 5주차 목표
  1th/week_5/Jay.md
Labels: 목표달성, 주간목표

#47 [1기] 6주차 목표
  1th/week_6/lena.md
Labels: 목표달성, 주간목표

#48 [1기] 6주차 목표
  1th/week_6/Solar.md
Labels: 주간목표, 피드백

#51 [1기] 6주차 목표
  1th/week_6/Ever.md
Labels: 목표수정, 주간목표, 피드백

#49 [1기] 6주차 목표
  1th/week_6/Poogle.md
Labels: 주간목표, 피드백

#56 [1기] 7주차 목표
  1th/week_7/Ever.md
Labels: 주간목표

#55 [1기] 7주차 목표
  1th/week_7/Poogle.md
Labels: 목표달성, 주간목표

#53 [1기] 7주차 목표
  1th/week_7/Solar.md
Labels: 목표달성, 주간목표
