Repository back-stage/WeekBack, pull requests merged in 2021-03, with the labels that each got.

#64 [1기] Jay 회고
  1th/week_1/Jay.md
  1th/week_2/Jay.md
  1th/week_3/Jay.md
  1th/week_4/Jay.md
  1th/week_5/Jay.md
  1th/week_6/Jay.md
  1th/week_7/Jay.md
Labels: 기수회고

#60 [1기] Solar 회고
  1th/week_1/Solar.md
  1th/week_1/Template.md
  1th/week_2/Solar.md
  1th/week_3/Solar.md
  1th/week_4/Solar.md
  1th/week_5/Solar.md
  1th/week_6/Solar.md
  1th/week_7/Solar.md
Labels: 기수회고

#67 [2기] 1주차 목표
  2nd/week_1/Poogle.md
Labels: 목표달성, 주간목표, 피드백

#70 [2기] 1주차 목표
  2nd/week_1/README.md
  2nd/week_1/lena.md
Labels: 주간목표, 피드백

#66 [2기] 1주차 목표
  2nd/week_1/Solar.md
Labels: 목표달성, 주간목표, 피드백

#69 [2기] 1주차 목표
  2nd/week_1/Ever.md
Labels: 주간목표, 피드백

#65 [2기] 1주차 목표
  2nd/week_1/Jay.md
Labels: 주간목표, 피드백

#76 [2기] 2주차 목표
  2nd/week_2/Solar.md
Labels: 목표달성, 주간목표, 피드백

#74 [2기] 2주차 목표
  2nd/week_2/README.md
  2nd/week_2/lena.md
Labels: 목표달성, 주간목표, 피드백

#77 [2기] 2주차 목표
  2nd/week_2/Poogle.md
Labels: 목표달성, 주간목표, 피드백

#73 [2기] 2주차 목표
  2nd/week_2/Jay.md
Labels: 목표달성, 목표수정, 주간목표, 피드백

#75 [2기] 2주차 목표
  2nd/week_2/Ever.md
Labels: 주간목표, 피드백

#79 [2기] 3주차 목표
  2nd/week_3/Solar.md
Labels: 주간목표, 피드백

#83 [2기] 3주차 목표
  2nd/week_3/Jay.md
Labels: 주간목표, 피드백

#80 [2기] 3주차 목표
  2nd/week_3/Poogle.md
Labels: 주간목표, 피드백
