Repository back-stage/WeekBack, pull requests merged in 2021-01, with the labels that each got.

#6 [1기] 1주차 목표
  1th/week_1/Jay.md
Labels: 목표달성, 주간목표

#7 [1기] 1주차 목표
  1th/week_1/Solar.md
  1th/week_1/Template.md
Labels: 목표달성, 주간목표

#19 [1기] 1주차 목표
  .all-contributorsrc
  .github/ISSUE_TEMPLATE/-team--title.md
  .github/contributing.md
  1th/week_1/Poogle.md
  README.md
Labels: 목표달성, 주간목표

#27 [1기] 2주차 목표
  1th/week_2/Poogle.md
Labels: 목표달성, 주간목표

#26 [1기] 2주차 목표
  1th/week_2/Solar.md
Labels: 목표달성, 주간목표, 피드백

#28 [1기] 2주차 목표
  1th/week_2/Jay.md
Labels: 주간목표, 피드백

#29 [1기] 2주차 목표
  1th/week_2/lena.md
Labels: 주간목표, 피드백

#31 [1기] 3주차 목표
  1th/week_3/Solar.md
Labels: 목표달성, 주간목표

#32 [1기] 3주차 목표
  1th/week_3/Poogle.md
  README.md
Labels: 목표달성, 주간목표, 피드백

#35 [1기] 3주차 목표
  1th/week_3/Jay.md
Labels: 주간목표, 피드백

#33 [1기] 3주차 목표
  1th/week_3/Ever.md
Labels: 주간목표
