Repository back-stage/WeekBack, pull requests merged in 2021-04, with the labels that each got.

#89 [2기] 4주차 목표
  2nd/week_4/Jay.md
Labels: 목표달성, 주간목표, 피드백

#87 [2기] 4주차 목표
  2nd/week_4/Poogle.md
Labels: 목표달성, 주간목표, 피드백

#88 [2기] 4주차 목표
  2nd/week_4/Ever.md
Labels: 주간목표, 피드백

#95 [2기] 5주차 목표
  2nd/week_2/Jay.md
  2nd/week_5/Jay.md
Labels: 목표달성, 주간목표, 피드백

#93 [2기] 5주차 목표
  2nd/week_5/Ever.md
Labels: 목표달성, 주간목표, 피드백

#91 [2기] 5주차 목표
  2nd/week_5/README.md
  2nd/week_5/lena.md
Labels: 목표달성, 주간목표, 피드백

#94 [2기] 5주차 목표
  2nd/week_5/Poogle.md
Labels: 주간목표, 피드백

#86 [2기] 4주차 목표
  2nd/week_4/Solar.md
Labels: 목표달성, 목표수정, 주간목표, 피드백

#101 [2기] 6주차 목표
  2nd/week_1/Poogle.md
  2nd/week_1/README.md
  2nd/week_2/Poogle.md
  2nd/week_2/README.md
  2nd/week_3/Poogle.md
  2nd/week_3/README.md
  2nd/week_4/Poogle.md
  2nd/week_4/README.md
  2nd/week_5/Poogle.md
  2nd/week_5/README.md
  2nd/week_6/README.md
  2nd/week_7/README.md
  2nd/week_8/README.md
Labels: 목표달성, 주간목표, 피드백

#99 [2기] 6주차 목표
  2nd/week_6/Jay.md
Labels: 주간목표, 피드백

#97 [2기] 6주차 목표
  2nd/week_6/README.md
  2nd/week_6/lena.md
Labels: 목표달성, 주간목표, 피드백

#111 [2기] 6주차 목표
  2nd/week_6/Poogle.md
Labels: 목표달성, 주간목표, 피드백

#100 [2기] 6주차 목표
  2nd/week_6/Ever.md
Labels: 주간목표, 피드백

#105 [2기] 7주차 목표
  2nd/week_7/Poogle.md
Labels: 목표달성, 목표수정, 주간목표, 피드백

#103 [2기] 7주차 목표
  2nd/week_7/Jay.md
Labels: 주간목표, 피드백

#112 [2기] 8주차 목표
  2nd/week_8/Poogle.md
Labels: 목표달성, 주간목표

#104 [2기] 7주차 목표
  2nd/week_7/README.md
  2nd/week_7/lena.md
Labels: 목표달성, 주간목표, 피드백

#113 [2기] 8주차 목표
  2nd/week_8/README.md
  2nd/week_8/lena.md
Labels: 주간목표

#114 [2기] 8주차 목표
  2nd/week_8/Jay.md
Labels: 주간목표

#106 [2기] 7주차 목표
  2nd/week_7/Ever.md
Labels: 목표달성, 주간목표, 피드백

#110 [2기] 8주차 목표
  2nd/week_8/Ever.md
Labels: 목표달성, 주간목표

#115 [2기] Poogle 회고
  2nd/week_1/Poogle.md
  2nd/week_1/README.md
  2nd/week_2/Poogle.md
  2nd/week_2/README.md
  2nd/week_3/Poogle.md
  2nd/week_3/README.md
  2nd/week_4/Poogle.md
  2nd/week_4/README.md
  2nd/week_5/Poogle.md
  2nd/week_5/README.md
  2nd/week_6/Poogle.md
  2nd/week_6/README.md
  2nd/week_7/Poogle.md
  2nd/week_7/README.md
  2nd/week_8/Poogle.md
  2nd/week_8/README.md
Labels: 기수회고

#117 [2기] Lena 회고
  1th/week_1/lena.md
  1th/week_2/lena.md
  1th/week_3/lena.md
  1th/week_4/lena.md
  1th/week_5/lena.md
  1th/week_6/lena.md
  1th/week_7/lena.md
  2nd/week_1/lena.md
  2nd/week_2/lena.md
  2nd/week_3/lena.md
  2nd/week_4/lena.md
  2nd/week_5/lena.md
  2nd/week_6/lena.md
  2nd/week_7/lena.md
  2nd/week_8/lena.md
Labels: 기수회고
